[project]
name = "py_leap_api"
version = "0.0.1"
authors = [
  { name="IperGiove", email="ipergiove@duck.com" },
]
description = "Library to interact with TryLeap API"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/IperGiove/py_leap_api"
"Bug Tracker" = "https://github.com/IperGiove/py_leap_api/issues"
